import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Sidebar from "./_components/Sidebar";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Textin - Chatting App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/icon.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <main className=" w-screen h-screen">
            <Header />
            <div className="h-[calc(100vh-56px)] flex">
              <Sidebar />
              {children}
            </div>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
